// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQAQFjZa5SJHS2Scy7kl3p9aFE5YT0Ojk',
    appId: '1:826388872613:android:db3f31c6830d281c023c4c',
    messagingSenderId: '826388872613',
    projectId: 'fitbody-8db66',
    storageBucket: 'fitbody-8db66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5FKcV1NhC2fcRtxb_vMmwDbDZzmWHeCc',
    appId: '1:826388872613:ios:914e7b8db79fc6ba023c4c',
    messagingSenderId: '826388872613',
    projectId: 'fitbody-8db66',
    storageBucket: 'fitbody-8db66.appspot.com',
    iosBundleId: 'com.fitnessdev.fitbody',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5FKcV1NhC2fcRtxb_vMmwDbDZzmWHeCc',
    appId: '1:826388872613:ios:914e7b8db79fc6ba023c4c',
    messagingSenderId: '826388872613',
    projectId: 'fitbody-8db66',
    storageBucket: 'fitbody-8db66.appspot.com',
    iosBundleId: 'com.fitnessdev.fitbody',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwygjZo0Slrt-yRrencaSSyST2L89X-_k',
    appId: '1:826388872613:web:06b2d38b1ecb1db5023c4c',
    messagingSenderId: '826388872613',
    projectId: 'fitbody-8db66',
    authDomain: 'fitbody-8db66.firebaseapp.com',
    storageBucket: 'fitbody-8db66.appspot.com',
    measurementId: 'G-MEXWFPRB5X',
  );
}
